# Generated by Django 4.1.2 on 2022-10-14 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('user_ID', models.IntegerField()),
                ('sc_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['sc_ID'],
            },
        ),
    ]
