# Generated by Django 4.1.1 on 2022-10-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='authorBio',
            new_name='AuthorBio',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='authorName',
            new_name='AuthorName',
        ),
    ]
